In [1]:
# importing the numpy library
import numpy as np

In [8]:
# numpy array creation
a = np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [14]:
# 2dimensional array creation
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0,1],b[0,2])

[[1 2 3]
 [4 5 6]]
(2, 3)
2 3


### Numpy array provide many functionality

In [16]:
# array with zero values
zero_array = np.zeros([2,2])
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [17]:
# Array of one value
ones_array = np.ones((1,2))
ones_array

array([[1., 1.]])

In [18]:
# Array filled with a constant
c = np.full([2,3],7)
print(c)

[[7 7 7]
 [7 7 7]]


In [20]:
# identity matrix array
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [23]:
# Creating a random array
random_array = np.random.random([2,2])
random_array

array([[0.42151801, 0.70840848],
       [0.65343142, 0.97041314]])

In [28]:
# 3 dimension array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# Slicing of array
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [33]:
# Using the scling for priting
print("a[0,1] = ",a[0,1])
print('b[0,0] = ',b[0,0])

a[0,1] =  2
b[0,0] =  2


In [50]:
# Sclicing the row1, row2 and row3
row_r1 = a[0,:]
row_r2 = a[1:2,:]
row_r3 = a[2:3,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
print(row_r3,row_r3.shape)

[1 2 3 4] (4,)
[[5 6 7 8]] (1, 4)
[[ 9 10 11 12]] (1, 4)


In [53]:
# Scling the columns from it
column_1 = a[:,1]
column_2 = a[:,1:2]
column_3 = a[:,2:3]
print(column_1,column_1.shape)
print(column_2,column_2.shape)
print(column_3,column_3.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 3]
 [ 7]
 [11]] (3, 1)


In [56]:
# Scling of array
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(a[[0,1,2],[0,1,0]])
print(a[0,0],a[1,1],a[2,0])

[1 4 5]
1 4 5


In [60]:
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[2 2]
[2 2]


In [61]:
# Four dimension array
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
b = np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [64]:
a[np.arange(4)]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
a = np.array([[1,2],[3,4],[5,6]])
bool_index = (a > 2)

In [66]:
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


In [67]:
# Boolean indexing
a[a>2]

array([3, 4, 5, 6])

In [79]:
x = np.array([4,5])
y = np.array([1.0,2.0])
z = np.array([1,2],dtype=np.int64)
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [80]:
# Subtraction
print(x-y)
print(np.subtract(x,y))

[3. 3.]
[3. 3.]


In [81]:
# Multiplication
print(x * y)
print(np.multiply(x,y))

[ 4. 10.]
[ 4. 10.]


In [82]:
# Square root of array numbers
np.sqrt(z)

array([1.        , 1.41421356])

In [86]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

y = np.array([9,10])
w = np.array([11,12])

In [89]:
# Element wise multiplication
print(y.dot(w))
print(np.dot(y,w))

219
219


In [90]:
# Matrix multiplication
print(y@w)

219


In [92]:
# Mutlipication of x, y
print(x.dot(y))
print(x@y)
print(np.dot(x,y))

[29 67]
[29 67]
[29 67]


In [94]:
z = np.array([[1,2],[3,4]])
print(np.sum(z))
print(np.sum(z,axis=0)) # row wise
print(np.sum(z,axis=1)) # column wise addiition

10
[4 6]
[3 7]
